### ISSUE TITLE
Revisión anteproyecto

### ISSUE THREAD

**Issue by rlopdav392** [Guisseee/TFG-Guillermo-Jauregui-Lahoz#2]
Buenas tardes Guillermo,

Te pasamos por aquí lo que hemos visto con respecto a la revisión:
Sobra el campo id_cliente de clases_semanales
El nombre de la tabla que siguen un mismo patrón
Las relaciones 1:1 entre el cliente y los distintos planes sugieren que cada cliente tiene un único plan durante todo el tiempo que esté en ese gimnasio, si cambias de plan se perdería la información asociada, habría que cambiar esa cardinalidad y añadir un campo fecha para almacenar esos históricos de los clientes.

Eso sería

Gracias!!!

**Comment by Guisseee** [comment]
Hola Rocio, buenos días.

Acabo de cambiar la entidad y la he corregido ya, ¿te paso una foto por
correo de la nueva o la mirais vosotras en el notion?

Saludos.

**Comment by rlopdav392** [comment]
lo miramos en el notion

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
